############# English navigation ##############

[[main]]
name = "Dataset"
weight = 1

[[main]]
name = "Overview"
url = "/dataset"
parent = "Dataset"
weight = 1

[[main]]
name = "Format"
url = "/format"
parent = "Dataset"
weight = 2

[[main]]
name = "Download"
url = "/download"
parent = "Dataset"
weight = 3

[[main]]
name = "Resources"
url = "/resources"
weight = 2

[[main]]
name = "Team"
url = "/team"
weight = 3

[[main]]
name = "Contact"
url = "/contact"
weight = 4

# footer menu
[[footer]]
name = "Contact"
url = "/contact"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "https://ori.ox.ac.uk/publications/datasets/robotcycle-ethics/"
weight = 3
