############# English navigation ##############

[[main]]
name = "Dataset"
weight = 1

[[main]]
name = "Download"
url = "/download"
parent = "Dataset"
weight = 1

[[main]]
name = "Contact"
url = "/contact"
weight = 2

# footer menu
[[footer]]
name = "Contact"
url = "/contact"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "https://ori.ox.ac.uk/publications/datasets/robotcycle-ethics/"
weight = 3
