######################## default configuration ####################
# The base URL of your site (required). This will be prepended to all relative URLs.
baseURL = "https://ori-mrg.github.io/robotcycle-dataset/"
# Title of your website (required).
title = "RobotCycle Dataset"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "America/New_York"
# post excerpt
summaryLength = 10 # see https://gohugo.io/content-management/excerpts/
# disable language
disableLanguages = [
] # example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = false #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage
# default language
defaultContentLanguage = 'en'
# defaultContentLanguageInSubdir need to be true if you want to use the language code as a subdirectory and language specific 404 page
defaultContentLanguageInSubdir = false

############################# Modules ############################
[module]
[[module.imports]]
path = "github.com/imfing/hextra"

############################ Markup ##############################
[markup]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
noClasses = false
lineNos = true
lineNumbersInTable = false
style = "github"

########################### Parameters ###########################
[params]
# Hextra theme specific parameters
navbar.displayTitle = false
navbar.displayLogo = true
navbar.displayThemeToggle = true
favicon = "/images/favicon.png"
page.width = "wide"

theme.default = "system"
theme.displayToggle = true

footer.displayCopyright = true
footer.displayPoweredBy = false

editPage.enable = false

search.enable = true
search.type = "flexsearch"

blog.list.displayTags = true

# Navbar logo configuration
[params.navbar.logo]
path = "images/logo.png"
dark = "images/logo-darkmode.png"
width = 128
height = 64

# Menu configuration for Hextra
[menu]
[[menu.main]]
name = "Dataset"
pageRef = "/"
weight = 10

[[menu.main]]
name = "Download"
pageRef = "/download"
weight = 20

[[menu.main]]
name = "Contact"
pageRef = "/contact"
weight = 30

############################# Outputs ############################
[outputs]
home = ["HTML", "RSS"]

